"""Adiciona funcionalidade de habilidades

Revision ID: 3673cd1c6eb7
Revises: 65f8a5d94307
Create Date: 2025-10-01 16:39:16.783384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3673cd1c6eb7'
down_revision = '65f8a5d94307'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habilidade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcao', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcao')
    )
    op.create_table('usuario_habilidades',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('habilidade_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['habilidade_id'], ['habilidade.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('usuario_id', 'habilidade_id')
    )
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuario', schema=None) as batch_op:
        batch_op.alter_column('is_admin',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('nome',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    op.drop_table('usuario_habilidades')
    op.drop_table('habilidade')
    # ### end Alembic commands ###
