"""Adiciona arquivamento e funcionalidades de editar/excluir missas

Revision ID: c6e413e0dae8
Revises: 3673cd1c6eb7
Create Date: 2025-10-01 16:59:35.128982

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6e413e0dae8'
down_revision = '3673cd1c6eb7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('arquivada', sa.Boolean(), nullable=False, server_default='0'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('missa', schema=None) as batch_op:
        batch_op.drop_column('arquivada')

    # ### end Alembic commands ###
